'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FACE_Gob_WS_pruebas
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://webservice.face.gob.es", ConfigurationName:="FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort", ProtectionLevel := System.Net.Security.ProtectionLevel.Sign)>  _
    Public Interface FacturaSSPPWebServiceProxyPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#enviarFactura", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function enviarFactura(ByVal request As FACE_Gob_WS_pruebas.EnviarFacturaRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.EnviarFacturaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#enviarFactura", ReplyAction:="*")>  _
        Function enviarFacturaAsync(ByVal request As FACE_Gob_WS_pruebas.EnviarFacturaRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.EnviarFacturaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarFactura", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function consultarFactura(ByVal numeroRegistro As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.ConsultarFacturaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarFactura", ReplyAction:="*")>  _
        Function consultarFacturaAsync(ByVal numeroRegistro As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarFacturaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#anularFactura", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function anularFactura(ByVal numeroRegistro As String, ByVal motivo As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.AnularFacturaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#anularFactura", ReplyAction:="*")>  _
        Function anularFacturaAsync(ByVal numeroRegistro As String, ByVal motivo As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.AnularFacturaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarEstados", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function consultarEstados() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.ConsultarEstadosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarEstados", ReplyAction:="*")>  _
        Function consultarEstadosAsync() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarEstadosResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarUnidades", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function consultarUnidades() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.ConsultarRelacionesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarUnidades", ReplyAction:="*")>  _
        Function consultarUnidadesAsync() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarRelacionesResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarNIFs", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function consultarNIFs() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.ConsultarNIFsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarNIFs", ReplyAction:="*")>  _
        Function consultarNIFsAsync() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarNIFsResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarAdministraciones", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function consultarAdministraciones() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.ConsultarAdministracionesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarAdministraciones", ReplyAction:="*")>  _
        Function consultarAdministracionesAsync() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarAdministracionesResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarAdministracionesRepositorio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function consultarAdministracionesRepositorio() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.ConsultarAdministracionesRepositorioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarAdministracionesRepositorio", ReplyAction:="*")>  _
        Function consultarAdministracionesRepositorioAsync() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarAdministracionesRepositorioResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarUnidadesPorAdministracion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function consultarUnidadesPorAdministracion(ByVal codigoDir As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.ConsultarRelacionesPorAdministracionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarUnidadesPorAdministracion", ReplyAction:="*")>  _
        Function consultarUnidadesPorAdministracionAsync(ByVal codigoDir As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarRelacionesPorAdministracionResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarNIFsPorAdministracion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true)>  _
        Function consultarNIFsPorAdministracion(ByVal codigoDir As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.ConsultarNIFsPorAdministracionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarNIFsPorAdministracion", ReplyAction:="*")>  _
        Function consultarNIFsPorAdministracionAsync(ByVal codigoDir As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarNIFsPorAdministracionResponse)
        
        'CODEGEN: El parámetro 'request' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarListadoFacturas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultarListadoFacturas(ByVal request As FACE_Gob_WS_pruebas.consultarListadoFacturasRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> FACE_Gob_WS_pruebas.consultarListadoFacturasResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://webservice.face.gob.es#consultarListadoFacturas", ReplyAction:="*")>  _
        Function consultarListadoFacturasAsync(ByVal request As FACE_Gob_WS_pruebas.consultarListadoFacturasRequest) As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.consultarListadoFacturasResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class EnviarFacturaRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private correoField As String
        
        Private facturaField As FacturaFile
        
        Private anexosField() As AnexoFile
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
                Me.RaisePropertyChanged("correo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property factura() As FacturaFile
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
                Me.RaisePropertyChanged("factura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("anexo", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property anexos() As AnexoFile()
            Get
                Return Me.anexosField
            End Get
            Set
                Me.anexosField = value
                Me.RaisePropertyChanged("anexos")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class FacturaFile
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private facturaField As String
        
        Private nombreField As String
        
        Private mimeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property factura() As String
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
                Me.RaisePropertyChanged("factura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mime() As String
            Get
                Return Me.mimeField
            End Get
            Set
                Me.mimeField = value
                Me.RaisePropertyChanged("mime")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarListadoFactura
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private facturaField As ConsultarFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property factura() As ConsultarFactura
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
                Me.RaisePropertyChanged("factura")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarFactura
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private numeroRegistroField As String
        
        Private tramitacionField As EstadoFactura
        
        Private anulacionField As EstadoFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroRegistro() As String
            Get
                Return Me.numeroRegistroField
            End Get
            Set
                Me.numeroRegistroField = value
                Me.RaisePropertyChanged("numeroRegistro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tramitacion() As EstadoFactura
            Get
                Return Me.tramitacionField
            End Get
            Set
                Me.tramitacionField = value
                Me.RaisePropertyChanged("tramitacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property anulacion() As EstadoFactura
            Get
                Return Me.anulacionField
            End Get
            Set
                Me.anulacionField = value
                Me.RaisePropertyChanged("anulacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class EstadoFactura
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private motivoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property motivo() As String
            Get
                Return Me.motivoField
            End Get
            Set
                Me.motivoField = value
                Me.RaisePropertyChanged("motivo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarListadoFacturaResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private facturasField() As ConsultarListadoFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("consultarListadoFactura", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property facturas() As ConsultarListadoFactura()
            Get
                Return Me.facturasField
            End Get
            Set
                Me.facturasField = value
                Me.RaisePropertyChanged("facturas")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class Resultado
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private codigoSeguimientoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property codigoSeguimiento() As String
            Get
                Return Me.codigoSeguimientoField
            End Get
            Set
                Me.codigoSeguimientoField = value
                Me.RaisePropertyChanged("codigoSeguimiento")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarNIFsPorAdministracionResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private nifsField() As OGNIFs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("info", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property nifs() As OGNIFs()
            Get
                Return Me.nifsField
            End Get
            Set
                Me.nifsField = value
                Me.RaisePropertyChanged("nifs")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class OGNIFs
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private organoGestorField As UnidadDir3
        
        Private nifField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property organoGestor() As UnidadDir3
            Get
                Return Me.organoGestorField
            End Get
            Set
                Me.organoGestorField = value
                Me.RaisePropertyChanged("organoGestor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nif() As String
            Get
                Return Me.nifField
            End Get
            Set
                Me.nifField = value
                Me.RaisePropertyChanged("nif")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class UnidadDir3
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private nombreField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarRelacionesPorAdministracionResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private relacionesField() As OGUTOC
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("relacion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property relaciones() As OGUTOC()
            Get
                Return Me.relacionesField
            End Get
            Set
                Me.relacionesField = value
                Me.RaisePropertyChanged("relaciones")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class OGUTOC
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private organoGestorField As UnidadDir3
        
        Private unidadTramitadoraField As UnidadDir3
        
        Private oficinaContableField As UnidadDir3
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property organoGestor() As UnidadDir3
            Get
                Return Me.organoGestorField
            End Get
            Set
                Me.organoGestorField = value
                Me.RaisePropertyChanged("organoGestor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property unidadTramitadora() As UnidadDir3
            Get
                Return Me.unidadTramitadoraField
            End Get
            Set
                Me.unidadTramitadoraField = value
                Me.RaisePropertyChanged("unidadTramitadora")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property oficinaContable() As UnidadDir3
            Get
                Return Me.oficinaContableField
            End Get
            Set
                Me.oficinaContableField = value
                Me.RaisePropertyChanged("oficinaContable")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarAdministracionesRepositorioResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private administracionesField() As UnidadDir3
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("administracion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property administraciones() As UnidadDir3()
            Get
                Return Me.administracionesField
            End Get
            Set
                Me.administracionesField = value
                Me.RaisePropertyChanged("administraciones")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarAdministracionesResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private administracionesField() As UnidadDir3
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("administracion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property administraciones() As UnidadDir3()
            Get
                Return Me.administracionesField
            End Get
            Set
                Me.administracionesField = value
                Me.RaisePropertyChanged("administraciones")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarNIFsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private nifsField() As OGNIFs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("info", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property nifs() As OGNIFs()
            Get
                Return Me.nifsField
            End Get
            Set
                Me.nifsField = value
                Me.RaisePropertyChanged("nifs")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarRelacionesResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private relacionesField() As OGUTOC
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("relacion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property relaciones() As OGUTOC()
            Get
                Return Me.relacionesField
            End Get
            Set
                Me.relacionesField = value
                Me.RaisePropertyChanged("relaciones")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class Estado
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreField As String
        
        Private codigoField As String
        
        Private descripcionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("descripcion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarEstadosResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private estadosField() As Estado
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("estado", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property estados() As Estado()
            Get
                Return Me.estadosField
            End Get
            Set
                Me.estadosField = value
                Me.RaisePropertyChanged("estados")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class AnularFactura
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private numeroRegistroField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroRegistro() As String
            Get
                Return Me.numeroRegistroField
            End Get
            Set
                Me.numeroRegistroField = value
                Me.RaisePropertyChanged("numeroRegistro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class AnularFacturaResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private facturaField As AnularFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property factura() As AnularFactura
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
                Me.RaisePropertyChanged("factura")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarFacturaResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private facturaField As ConsultarFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property factura() As ConsultarFactura
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
                Me.RaisePropertyChanged("factura")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class EnviarFactura
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private numeroRegistroField As String
        
        Private organoGestorField As String
        
        Private unidadTramitadoraField As String
        
        Private oficinaContableField As String
        
        Private identificadorEmisorField As String
        
        Private numeroFacturaField As String
        
        Private serieFacturaField As String
        
        Private fechaRecepcionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroRegistro() As String
            Get
                Return Me.numeroRegistroField
            End Get
            Set
                Me.numeroRegistroField = value
                Me.RaisePropertyChanged("numeroRegistro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property organoGestor() As String
            Get
                Return Me.organoGestorField
            End Get
            Set
                Me.organoGestorField = value
                Me.RaisePropertyChanged("organoGestor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property unidadTramitadora() As String
            Get
                Return Me.unidadTramitadoraField
            End Get
            Set
                Me.unidadTramitadoraField = value
                Me.RaisePropertyChanged("unidadTramitadora")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property oficinaContable() As String
            Get
                Return Me.oficinaContableField
            End Get
            Set
                Me.oficinaContableField = value
                Me.RaisePropertyChanged("oficinaContable")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property identificadorEmisor() As String
            Get
                Return Me.identificadorEmisorField
            End Get
            Set
                Me.identificadorEmisorField = value
                Me.RaisePropertyChanged("identificadorEmisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property numeroFactura() As String
            Get
                Return Me.numeroFacturaField
            End Get
            Set
                Me.numeroFacturaField = value
                Me.RaisePropertyChanged("numeroFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property serieFactura() As String
            Get
                Return Me.serieFacturaField
            End Get
            Set
                Me.serieFacturaField = value
                Me.RaisePropertyChanged("serieFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaRecepcion() As String
            Get
                Return Me.fechaRecepcionField
            End Get
            Set
                Me.fechaRecepcionField = value
                Me.RaisePropertyChanged("fechaRecepcion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class EnviarFacturaResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As Resultado
        
        Private facturaField As EnviarFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property factura() As EnviarFactura
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
                Me.RaisePropertyChanged("factura")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class AnexoFile
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anexoField As String
        
        Private nombreField As String
        
        Private mimeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property anexo() As String
            Get
                Return Me.anexoField
            End Get
            Set
                Me.anexoField = value
                Me.RaisePropertyChanged("anexo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mime() As String
            Get
                Return Me.mimeField
            End Get
            Set
                Me.mimeField = value
                Me.RaisePropertyChanged("mime")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consultarListadoFacturas", WrapperNamespace:="https://webservice.face.gob.es", IsWrapped:=true)>  _
    Partial Public Class consultarListadoFacturasRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0),  _
         System.Xml.Serialization.XmlArrayAttribute(),  _
         System.Xml.Serialization.XmlArrayItemAttribute("numeroRegistro", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public request() As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal request() As String)
            MyBase.New
            Me.request = request
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consultarListadoFacturasResponse", WrapperNamespace:="https://webservice.face.gob.es", IsWrapped:=true)>  _
    Partial Public Class consultarListadoFacturasResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return] As FACE_Gob_WS_pruebas.ConsultarListadoFacturaResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As FACE_Gob_WS_pruebas.ConsultarListadoFacturaResponse)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FacturaSSPPWebServiceProxyPortChannel
        Inherits FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FacturaSSPPWebServiceProxyPortClient
        Inherits System.ServiceModel.ClientBase(Of FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort)
        Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function enviarFactura(ByVal request As FACE_Gob_WS_pruebas.EnviarFacturaRequest) As FACE_Gob_WS_pruebas.EnviarFacturaResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.enviarFactura
            Return MyBase.Channel.enviarFactura(request)
        End Function
        
        Public Function enviarFacturaAsync(ByVal request As FACE_Gob_WS_pruebas.EnviarFacturaRequest) As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.EnviarFacturaResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.enviarFacturaAsync
            Return MyBase.Channel.enviarFacturaAsync(request)
        End Function
        
        Public Function consultarFactura(ByVal numeroRegistro As String) As FACE_Gob_WS_pruebas.ConsultarFacturaResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarFactura
            Return MyBase.Channel.consultarFactura(numeroRegistro)
        End Function
        
        Public Function consultarFacturaAsync(ByVal numeroRegistro As String) As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarFacturaResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarFacturaAsync
            Return MyBase.Channel.consultarFacturaAsync(numeroRegistro)
        End Function
        
        Public Function anularFactura(ByVal numeroRegistro As String, ByVal motivo As String) As FACE_Gob_WS_pruebas.AnularFacturaResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.anularFactura
            Return MyBase.Channel.anularFactura(numeroRegistro, motivo)
        End Function
        
        Public Function anularFacturaAsync(ByVal numeroRegistro As String, ByVal motivo As String) As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.AnularFacturaResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.anularFacturaAsync
            Return MyBase.Channel.anularFacturaAsync(numeroRegistro, motivo)
        End Function
        
        Public Function consultarEstados() As FACE_Gob_WS_pruebas.ConsultarEstadosResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarEstados
            Return MyBase.Channel.consultarEstados
        End Function
        
        Public Function consultarEstadosAsync() As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarEstadosResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarEstadosAsync
            Return MyBase.Channel.consultarEstadosAsync
        End Function
        
        Public Function consultarUnidades() As FACE_Gob_WS_pruebas.ConsultarRelacionesResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarUnidades
            Return MyBase.Channel.consultarUnidades
        End Function
        
        Public Function consultarUnidadesAsync() As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarRelacionesResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarUnidadesAsync
            Return MyBase.Channel.consultarUnidadesAsync
        End Function
        
        Public Function consultarNIFs() As FACE_Gob_WS_pruebas.ConsultarNIFsResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarNIFs
            Return MyBase.Channel.consultarNIFs
        End Function
        
        Public Function consultarNIFsAsync() As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarNIFsResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarNIFsAsync
            Return MyBase.Channel.consultarNIFsAsync
        End Function
        
        Public Function consultarAdministraciones() As FACE_Gob_WS_pruebas.ConsultarAdministracionesResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarAdministraciones
            Return MyBase.Channel.consultarAdministraciones
        End Function
        
        Public Function consultarAdministracionesAsync() As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarAdministracionesResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarAdministracionesAsync
            Return MyBase.Channel.consultarAdministracionesAsync
        End Function
        
        Public Function consultarAdministracionesRepositorio() As FACE_Gob_WS_pruebas.ConsultarAdministracionesRepositorioResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarAdministracionesRepositorio
            Return MyBase.Channel.consultarAdministracionesRepositorio
        End Function
        
        Public Function consultarAdministracionesRepositorioAsync() As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarAdministracionesRepositorioResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarAdministracionesRepositorioAsync
            Return MyBase.Channel.consultarAdministracionesRepositorioAsync
        End Function
        
        Public Function consultarUnidadesPorAdministracion(ByVal codigoDir As String) As FACE_Gob_WS_pruebas.ConsultarRelacionesPorAdministracionResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarUnidadesPorAdministracion
            Return MyBase.Channel.consultarUnidadesPorAdministracion(codigoDir)
        End Function
        
        Public Function consultarUnidadesPorAdministracionAsync(ByVal codigoDir As String) As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarRelacionesPorAdministracionResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarUnidadesPorAdministracionAsync
            Return MyBase.Channel.consultarUnidadesPorAdministracionAsync(codigoDir)
        End Function
        
        Public Function consultarNIFsPorAdministracion(ByVal codigoDir As String) As FACE_Gob_WS_pruebas.ConsultarNIFsPorAdministracionResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarNIFsPorAdministracion
            Return MyBase.Channel.consultarNIFsPorAdministracion(codigoDir)
        End Function
        
        Public Function consultarNIFsPorAdministracionAsync(ByVal codigoDir As String) As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.ConsultarNIFsPorAdministracionResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarNIFsPorAdministracionAsync
            Return MyBase.Channel.consultarNIFsPorAdministracionAsync(codigoDir)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FACE_Gob_WS_pruebas_FacturaSSPPWebServiceProxyPort_consultarListadoFacturas(ByVal request As FACE_Gob_WS_pruebas.consultarListadoFacturasRequest) As FACE_Gob_WS_pruebas.consultarListadoFacturasResponse Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarListadoFacturas
            Return MyBase.Channel.consultarListadoFacturas(request)
        End Function
        
        Public Function consultarListadoFacturas(ByVal request() As String) As FACE_Gob_WS_pruebas.ConsultarListadoFacturaResponse
            Dim inValue As FACE_Gob_WS_pruebas.consultarListadoFacturasRequest = New FACE_Gob_WS_pruebas.consultarListadoFacturasRequest()
            inValue.request = request
            Dim retVal As FACE_Gob_WS_pruebas.consultarListadoFacturasResponse = CType(Me,FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort).consultarListadoFacturas(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FACE_Gob_WS_pruebas_FacturaSSPPWebServiceProxyPort_consultarListadoFacturasAsync(ByVal request As FACE_Gob_WS_pruebas.consultarListadoFacturasRequest) As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.consultarListadoFacturasResponse) Implements FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort.consultarListadoFacturasAsync
            Return MyBase.Channel.consultarListadoFacturasAsync(request)
        End Function
        
        Public Function consultarListadoFacturasAsync(ByVal request() As String) As System.Threading.Tasks.Task(Of FACE_Gob_WS_pruebas.consultarListadoFacturasResponse)
            Dim inValue As FACE_Gob_WS_pruebas.consultarListadoFacturasRequest = New FACE_Gob_WS_pruebas.consultarListadoFacturasRequest()
            inValue.request = request
            Return CType(Me,FACE_Gob_WS_pruebas.FacturaSSPPWebServiceProxyPort).consultarListadoFacturasAsync(inValue)
        End Function
    End Class
End Namespace
