'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace es.gob.face.webservice
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FacturaSSPPWebServiceProxyBinding", [Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class FacturaSSPPWebServiceProxyService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private enviarFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private anularFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarEstadosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarUnidadesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarNIFsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarAdministracionesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarAdministracionesRepositorioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarUnidadesPorAdministracionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarNIFsPorAdministracionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarListadoFacturasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.GestionFacturacion.My.MySettings.Default.GestionFacturacion_es_gob_face_webservice_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event enviarFacturaCompleted As enviarFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarFacturaCompleted As consultarFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event anularFacturaCompleted As anularFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarEstadosCompleted As consultarEstadosCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarUnidadesCompleted As consultarUnidadesCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarNIFsCompleted As consultarNIFsCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarAdministracionesCompleted As consultarAdministracionesCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarAdministracionesRepositorioCompleted As consultarAdministracionesRepositorioCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarUnidadesPorAdministracionCompleted As consultarUnidadesPorAdministracionCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarNIFsPorAdministracionCompleted As consultarNIFsPorAdministracionCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarListadoFacturasCompleted As consultarListadoFacturasCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#enviarFactura", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function enviarFactura(ByVal request As EnviarFacturaRequest) As <System.Xml.Serialization.XmlElementAttribute("return")> EnviarFacturaResponse
            Dim results() As Object = Me.Invoke("enviarFactura", New Object() {request})
            Return CType(results(0),EnviarFacturaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub enviarFacturaAsync(ByVal request As EnviarFacturaRequest)
            Me.enviarFacturaAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub enviarFacturaAsync(ByVal request As EnviarFacturaRequest, ByVal userState As Object)
            If (Me.enviarFacturaOperationCompleted Is Nothing) Then
                Me.enviarFacturaOperationCompleted = AddressOf Me.OnenviarFacturaOperationCompleted
            End If
            Me.InvokeAsync("enviarFactura", New Object() {request}, Me.enviarFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnenviarFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.enviarFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent enviarFacturaCompleted(Me, New enviarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarFactura", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function consultarFactura(ByVal numeroRegistro As String) As <System.Xml.Serialization.XmlElementAttribute("return")> ConsultarFacturaResponse
            Dim results() As Object = Me.Invoke("consultarFactura", New Object() {numeroRegistro})
            Return CType(results(0),ConsultarFacturaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarFacturaAsync(ByVal numeroRegistro As String)
            Me.consultarFacturaAsync(numeroRegistro, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarFacturaAsync(ByVal numeroRegistro As String, ByVal userState As Object)
            If (Me.consultarFacturaOperationCompleted Is Nothing) Then
                Me.consultarFacturaOperationCompleted = AddressOf Me.OnconsultarFacturaOperationCompleted
            End If
            Me.InvokeAsync("consultarFactura", New Object() {numeroRegistro}, Me.consultarFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarFacturaCompleted(Me, New consultarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#anularFactura", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function anularFactura(ByVal numeroRegistro As String, ByVal motivo As String) As <System.Xml.Serialization.XmlElementAttribute("return")> AnularFacturaResponse
            Dim results() As Object = Me.Invoke("anularFactura", New Object() {numeroRegistro, motivo})
            Return CType(results(0),AnularFacturaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub anularFacturaAsync(ByVal numeroRegistro As String, ByVal motivo As String)
            Me.anularFacturaAsync(numeroRegistro, motivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub anularFacturaAsync(ByVal numeroRegistro As String, ByVal motivo As String, ByVal userState As Object)
            If (Me.anularFacturaOperationCompleted Is Nothing) Then
                Me.anularFacturaOperationCompleted = AddressOf Me.OnanularFacturaOperationCompleted
            End If
            Me.InvokeAsync("anularFactura", New Object() {numeroRegistro, motivo}, Me.anularFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnanularFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.anularFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent anularFacturaCompleted(Me, New anularFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarEstados", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function consultarEstados() As <System.Xml.Serialization.XmlElementAttribute("return")> ConsultarEstadosResponse
            Dim results() As Object = Me.Invoke("consultarEstados", New Object(-1) {})
            Return CType(results(0),ConsultarEstadosResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarEstadosAsync()
            Me.consultarEstadosAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarEstadosAsync(ByVal userState As Object)
            If (Me.consultarEstadosOperationCompleted Is Nothing) Then
                Me.consultarEstadosOperationCompleted = AddressOf Me.OnconsultarEstadosOperationCompleted
            End If
            Me.InvokeAsync("consultarEstados", New Object(-1) {}, Me.consultarEstadosOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarEstadosOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarEstadosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarEstadosCompleted(Me, New consultarEstadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarUnidades", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function consultarUnidades() As <System.Xml.Serialization.XmlElementAttribute("return")> ConsultarRelacionesResponse
            Dim results() As Object = Me.Invoke("consultarUnidades", New Object(-1) {})
            Return CType(results(0),ConsultarRelacionesResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarUnidadesAsync()
            Me.consultarUnidadesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarUnidadesAsync(ByVal userState As Object)
            If (Me.consultarUnidadesOperationCompleted Is Nothing) Then
                Me.consultarUnidadesOperationCompleted = AddressOf Me.OnconsultarUnidadesOperationCompleted
            End If
            Me.InvokeAsync("consultarUnidades", New Object(-1) {}, Me.consultarUnidadesOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarUnidadesOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarUnidadesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarUnidadesCompleted(Me, New consultarUnidadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarNIFs", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function consultarNIFs() As <System.Xml.Serialization.XmlElementAttribute("return")> ConsultarNIFsResponse
            Dim results() As Object = Me.Invoke("consultarNIFs", New Object(-1) {})
            Return CType(results(0),ConsultarNIFsResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarNIFsAsync()
            Me.consultarNIFsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarNIFsAsync(ByVal userState As Object)
            If (Me.consultarNIFsOperationCompleted Is Nothing) Then
                Me.consultarNIFsOperationCompleted = AddressOf Me.OnconsultarNIFsOperationCompleted
            End If
            Me.InvokeAsync("consultarNIFs", New Object(-1) {}, Me.consultarNIFsOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarNIFsOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarNIFsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarNIFsCompleted(Me, New consultarNIFsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarAdministraciones", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function consultarAdministraciones() As <System.Xml.Serialization.XmlElementAttribute("return")> ConsultarAdministracionesResponse
            Dim results() As Object = Me.Invoke("consultarAdministraciones", New Object(-1) {})
            Return CType(results(0),ConsultarAdministracionesResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarAdministracionesAsync()
            Me.consultarAdministracionesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarAdministracionesAsync(ByVal userState As Object)
            If (Me.consultarAdministracionesOperationCompleted Is Nothing) Then
                Me.consultarAdministracionesOperationCompleted = AddressOf Me.OnconsultarAdministracionesOperationCompleted
            End If
            Me.InvokeAsync("consultarAdministraciones", New Object(-1) {}, Me.consultarAdministracionesOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarAdministracionesOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarAdministracionesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarAdministracionesCompleted(Me, New consultarAdministracionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarAdministracionesRepositorio", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function consultarAdministracionesRepositorio() As <System.Xml.Serialization.XmlElementAttribute("return")> ConsultarAdministracionesRepositorioResponse
            Dim results() As Object = Me.Invoke("consultarAdministracionesRepositorio", New Object(-1) {})
            Return CType(results(0),ConsultarAdministracionesRepositorioResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarAdministracionesRepositorioAsync()
            Me.consultarAdministracionesRepositorioAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarAdministracionesRepositorioAsync(ByVal userState As Object)
            If (Me.consultarAdministracionesRepositorioOperationCompleted Is Nothing) Then
                Me.consultarAdministracionesRepositorioOperationCompleted = AddressOf Me.OnconsultarAdministracionesRepositorioOperationCompleted
            End If
            Me.InvokeAsync("consultarAdministracionesRepositorio", New Object(-1) {}, Me.consultarAdministracionesRepositorioOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarAdministracionesRepositorioOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarAdministracionesRepositorioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarAdministracionesRepositorioCompleted(Me, New consultarAdministracionesRepositorioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarUnidadesPorAdministracion", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function consultarUnidadesPorAdministracion(ByVal codigoDir As String) As <System.Xml.Serialization.XmlElementAttribute("return")> ConsultarRelacionesPorAdministracionResponse
            Dim results() As Object = Me.Invoke("consultarUnidadesPorAdministracion", New Object() {codigoDir})
            Return CType(results(0),ConsultarRelacionesPorAdministracionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarUnidadesPorAdministracionAsync(ByVal codigoDir As String)
            Me.consultarUnidadesPorAdministracionAsync(codigoDir, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarUnidadesPorAdministracionAsync(ByVal codigoDir As String, ByVal userState As Object)
            If (Me.consultarUnidadesPorAdministracionOperationCompleted Is Nothing) Then
                Me.consultarUnidadesPorAdministracionOperationCompleted = AddressOf Me.OnconsultarUnidadesPorAdministracionOperationCompleted
            End If
            Me.InvokeAsync("consultarUnidadesPorAdministracion", New Object() {codigoDir}, Me.consultarUnidadesPorAdministracionOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarUnidadesPorAdministracionOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarUnidadesPorAdministracionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarUnidadesPorAdministracionCompleted(Me, New consultarUnidadesPorAdministracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarNIFsPorAdministracion", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function consultarNIFsPorAdministracion(ByVal codigoDir As String) As <System.Xml.Serialization.XmlElementAttribute("return")> ConsultarNIFsPorAdministracionResponse
            Dim results() As Object = Me.Invoke("consultarNIFsPorAdministracion", New Object() {codigoDir})
            Return CType(results(0),ConsultarNIFsPorAdministracionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarNIFsPorAdministracionAsync(ByVal codigoDir As String)
            Me.consultarNIFsPorAdministracionAsync(codigoDir, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarNIFsPorAdministracionAsync(ByVal codigoDir As String, ByVal userState As Object)
            If (Me.consultarNIFsPorAdministracionOperationCompleted Is Nothing) Then
                Me.consultarNIFsPorAdministracionOperationCompleted = AddressOf Me.OnconsultarNIFsPorAdministracionOperationCompleted
            End If
            Me.InvokeAsync("consultarNIFsPorAdministracion", New Object() {codigoDir}, Me.consultarNIFsPorAdministracionOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarNIFsPorAdministracionOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarNIFsPorAdministracionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarNIFsPorAdministracionCompleted(Me, New consultarNIFsPorAdministracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarListadoFacturas", RequestNamespace:="https://webservice.face.gob.es", ResponseNamespace:="https://webservice.face.gob.es", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function consultarListadoFacturas(<System.Xml.Serialization.XmlArrayItemAttribute("numeroRegistro", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)> ByVal request() As String) As <System.Xml.Serialization.XmlElementAttribute("return")> ConsultarListadoFacturaResponse
            Dim results() As Object = Me.Invoke("consultarListadoFacturas", New Object() {request})
            Return CType(results(0),ConsultarListadoFacturaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarListadoFacturasAsync(ByVal request() As String)
            Me.consultarListadoFacturasAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarListadoFacturasAsync(ByVal request() As String, ByVal userState As Object)
            If (Me.consultarListadoFacturasOperationCompleted Is Nothing) Then
                Me.consultarListadoFacturasOperationCompleted = AddressOf Me.OnconsultarListadoFacturasOperationCompleted
            End If
            Me.InvokeAsync("consultarListadoFacturas", New Object() {request}, Me.consultarListadoFacturasOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarListadoFacturasOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarListadoFacturasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarListadoFacturasCompleted(Me, New consultarListadoFacturasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class EnviarFacturaRequest
        
        Private correoField As String
        
        Private facturaField As FacturaFile
        
        Private anexosField() As AnexoFile
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property factura() As FacturaFile
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("anexo", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property anexos() As AnexoFile()
            Get
                Return Me.anexosField
            End Get
            Set
                Me.anexosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class FacturaFile
        
        Private facturaField As String
        
        Private nombreField As String
        
        Private mimeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property factura() As String
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mime() As String
            Get
                Return Me.mimeField
            End Get
            Set
                Me.mimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarListadoFactura
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private facturaField As ConsultarFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property factura() As ConsultarFactura
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarFactura
        
        Private numeroRegistroField As String
        
        Private tramitacionField As EstadoFactura
        
        Private anulacionField As EstadoFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroRegistro() As String
            Get
                Return Me.numeroRegistroField
            End Get
            Set
                Me.numeroRegistroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tramitacion() As EstadoFactura
            Get
                Return Me.tramitacionField
            End Get
            Set
                Me.tramitacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property anulacion() As EstadoFactura
            Get
                Return Me.anulacionField
            End Get
            Set
                Me.anulacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class EstadoFactura
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private motivoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property motivo() As String
            Get
                Return Me.motivoField
            End Get
            Set
                Me.motivoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarListadoFacturaResponse
        
        Private resultadoField As Resultado
        
        Private facturasField() As ConsultarListadoFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("consultarListadoFactura", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property facturas() As ConsultarListadoFactura()
            Get
                Return Me.facturasField
            End Get
            Set
                Me.facturasField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class Resultado
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private codigoSeguimientoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property codigoSeguimiento() As String
            Get
                Return Me.codigoSeguimientoField
            End Get
            Set
                Me.codigoSeguimientoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarNIFsPorAdministracionResponse
        
        Private resultadoField As Resultado
        
        Private nifsField() As OGNIFs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("info", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property nifs() As OGNIFs()
            Get
                Return Me.nifsField
            End Get
            Set
                Me.nifsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class OGNIFs
        
        Private organoGestorField As UnidadDir3
        
        Private nifField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property organoGestor() As UnidadDir3
            Get
                Return Me.organoGestorField
            End Get
            Set
                Me.organoGestorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nif() As String
            Get
                Return Me.nifField
            End Get
            Set
                Me.nifField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class UnidadDir3
        
        Private codigoField As String
        
        Private nombreField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarRelacionesPorAdministracionResponse
        
        Private resultadoField As Resultado
        
        Private relacionesField() As OGUTOC
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("relacion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property relaciones() As OGUTOC()
            Get
                Return Me.relacionesField
            End Get
            Set
                Me.relacionesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class OGUTOC
        
        Private organoGestorField As UnidadDir3
        
        Private unidadTramitadoraField As UnidadDir3
        
        Private oficinaContableField As UnidadDir3
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property organoGestor() As UnidadDir3
            Get
                Return Me.organoGestorField
            End Get
            Set
                Me.organoGestorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property unidadTramitadora() As UnidadDir3
            Get
                Return Me.unidadTramitadoraField
            End Get
            Set
                Me.unidadTramitadoraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property oficinaContable() As UnidadDir3
            Get
                Return Me.oficinaContableField
            End Get
            Set
                Me.oficinaContableField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarAdministracionesRepositorioResponse
        
        Private resultadoField As Resultado
        
        Private administracionesField() As UnidadDir3
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("administracion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property administraciones() As UnidadDir3()
            Get
                Return Me.administracionesField
            End Get
            Set
                Me.administracionesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarAdministracionesResponse
        
        Private resultadoField As Resultado
        
        Private administracionesField() As UnidadDir3
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("administracion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property administraciones() As UnidadDir3()
            Get
                Return Me.administracionesField
            End Get
            Set
                Me.administracionesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarNIFsResponse
        
        Private resultadoField As Resultado
        
        Private nifsField() As OGNIFs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("info", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property nifs() As OGNIFs()
            Get
                Return Me.nifsField
            End Get
            Set
                Me.nifsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarRelacionesResponse
        
        Private resultadoField As Resultado
        
        Private relacionesField() As OGUTOC
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("relacion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property relaciones() As OGUTOC()
            Get
                Return Me.relacionesField
            End Get
            Set
                Me.relacionesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class Estado
        
        Private nombreField As String
        
        Private codigoField As String
        
        Private descripcionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarEstadosResponse
        
        Private resultadoField As Resultado
        
        Private estadosField() As Estado
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("estado", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property estados() As Estado()
            Get
                Return Me.estadosField
            End Get
            Set
                Me.estadosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class AnularFactura
        
        Private numeroRegistroField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroRegistro() As String
            Get
                Return Me.numeroRegistroField
            End Get
            Set
                Me.numeroRegistroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class AnularFacturaResponse
        
        Private resultadoField As Resultado
        
        Private facturaField As AnularFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property factura() As AnularFactura
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class ConsultarFacturaResponse
        
        Private resultadoField As Resultado
        
        Private facturaField As ConsultarFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property factura() As ConsultarFactura
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class EnviarFactura
        
        Private numeroRegistroField As String
        
        Private organoGestorField As String
        
        Private unidadTramitadoraField As String
        
        Private oficinaContableField As String
        
        Private identificadorEmisorField As String
        
        Private numeroFacturaField As String
        
        Private serieFacturaField As String
        
        Private fechaRecepcionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroRegistro() As String
            Get
                Return Me.numeroRegistroField
            End Get
            Set
                Me.numeroRegistroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property organoGestor() As String
            Get
                Return Me.organoGestorField
            End Get
            Set
                Me.organoGestorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property unidadTramitadora() As String
            Get
                Return Me.unidadTramitadoraField
            End Get
            Set
                Me.unidadTramitadoraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property oficinaContable() As String
            Get
                Return Me.oficinaContableField
            End Get
            Set
                Me.oficinaContableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property identificadorEmisor() As String
            Get
                Return Me.identificadorEmisorField
            End Get
            Set
                Me.identificadorEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property numeroFactura() As String
            Get
                Return Me.numeroFacturaField
            End Get
            Set
                Me.numeroFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property serieFactura() As String
            Get
                Return Me.serieFacturaField
            End Get
            Set
                Me.serieFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaRecepcion() As String
            Get
                Return Me.fechaRecepcionField
            End Get
            Set
                Me.fechaRecepcionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class EnviarFacturaResponse
        
        Private resultadoField As Resultado
        
        Private facturaField As EnviarFactura
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property resultado() As Resultado
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property factura() As EnviarFactura
            Get
                Return Me.facturaField
            End Get
            Set
                Me.facturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://webservice.face.gob.es")>  _
    Partial Public Class AnexoFile
        
        Private anexoField As String
        
        Private nombreField As String
        
        Private mimeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property anexo() As String
            Get
                Return Me.anexoField
            End Get
            Set
                Me.anexoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mime() As String
            Get
                Return Me.mimeField
            End Get
            Set
                Me.mimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub enviarFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As enviarFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class enviarFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EnviarFacturaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EnviarFacturaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultarFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As consultarFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarFacturaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarFacturaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub anularFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As anularFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class anularFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AnularFacturaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AnularFacturaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultarEstadosCompletedEventHandler(ByVal sender As Object, ByVal e As consultarEstadosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarEstadosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarEstadosResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarEstadosResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultarUnidadesCompletedEventHandler(ByVal sender As Object, ByVal e As consultarUnidadesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarUnidadesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarRelacionesResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarRelacionesResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultarNIFsCompletedEventHandler(ByVal sender As Object, ByVal e As consultarNIFsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarNIFsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarNIFsResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarNIFsResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultarAdministracionesCompletedEventHandler(ByVal sender As Object, ByVal e As consultarAdministracionesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarAdministracionesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarAdministracionesResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarAdministracionesResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultarAdministracionesRepositorioCompletedEventHandler(ByVal sender As Object, ByVal e As consultarAdministracionesRepositorioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarAdministracionesRepositorioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarAdministracionesRepositorioResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarAdministracionesRepositorioResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultarUnidadesPorAdministracionCompletedEventHandler(ByVal sender As Object, ByVal e As consultarUnidadesPorAdministracionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarUnidadesPorAdministracionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarRelacionesPorAdministracionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarRelacionesPorAdministracionResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultarNIFsPorAdministracionCompletedEventHandler(ByVal sender As Object, ByVal e As consultarNIFsPorAdministracionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarNIFsPorAdministracionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarNIFsPorAdministracionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarNIFsPorAdministracionResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultarListadoFacturasCompletedEventHandler(ByVal sender As Object, ByVal e As consultarListadoFacturasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarListadoFacturasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarListadoFacturaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarListadoFacturaResponse)
            End Get
        End Property
    End Class
End Namespace
